// Code generated by gen_formats.go from decimal64_arith.go; DO NOT EDIT.

package decimal

// Add32 returns the sum x + y.
func (c *Context) Add32(x, y Decimal32) Decimal32 {
	return pack32(c.add(&format32, x.unpack(), y.unpack()))
}

// Sub32 returns the difference x - y.
func (c *Context) Sub32(x, y Decimal32) Decimal32 {
	return pack32(c.sub(&format32, x.unpack(), y.unpack()))
}

// Mul32 returns the product x × y.
func (c *Context) Mul32(x, y Decimal32) Decimal32 {
	return pack32(c.mul(&format32, x.unpack(), y.unpack()))
}

// Quo32 returns the quotient x / y.
func (c *Context) Quo32(x, y Decimal32) Decimal32 {
	return pack32(c.quo(&format32, x.unpack(), y.unpack()))
}

// FMA32 returns the fused multiply-add x × y + z: the exact product is added
// to z and the sum rounded once.
func (c *Context) FMA32(x, y, z Decimal32) Decimal32 {
	return pack32(c.fma(&format32, x.unpack(), y.unpack(), z.unpack()))
}

// Sqrt32 returns the square root of x, correctly rounded. The square root
// of a negative number other than -0 is a NaN and raises Invalid.
func (c *Context) Sqrt32(x Decimal32) Decimal32 {
	return pack32(c.sqrt(&format32, x.unpack()))
}

// FMA returns the fused multiply-add x × y + z, rounded once, to nearest
// even.
func (x Decimal32) FMA(y, z Decimal32) Decimal32 {
	var c Context
	return c.FMA32(x, y, z)
}

// Sqrt returns the square root of x, rounded to nearest even.
//
// The exponent of an exact square root is as close to half the exponent of
// x as the result allows, so the square root of 4.00 is 2.0.
func (x Decimal32) Sqrt() Decimal32 {
	var c Context
	return c.Sqrt32(x)
}

// Add returns the sum x + y, rounded to nearest even.
//
// The exponent of an exact sum is the smaller of the operands' exponents,
// so 1.5 + 0.25 is 1.75 and 1.50 + 1 is 2.50.
func (x Decimal32) Add(y Decimal32) Decimal32 {
	var c Context
	return c.Add32(x, y)
}

// Sub returns the difference x - y, rounded to nearest even.
func (x Decimal32) Sub(y Decimal32) Decimal32 {
	var c Context
	return c.Sub32(x, y)
}

// Mul returns the product x × y, rounded to nearest even.
//
// The exponent of an exact product is the sum of the operands' exponents,
// so 1.5 × 2.00 is 3.000.
func (x Decimal32) Mul(y Decimal32) Decimal32 {
	var c Context
	return c.Mul32(x, y)
}

// Quo returns the quotient x / y, rounded to nearest even. Division of a
// finite non-zero number by zero returns an infinity.
//
// The exponent of an exact quotient is as close to the difference of the
// operands' exponents as the result allows, so 6.0 / 2 is 3.0 and 1 / 4 is
// 0.25.
func (x Decimal32) Quo(y Decimal32) Decimal32 {
	var c Context
	return c.Quo32(x, y)
}
