// Code generated by gen_formats.go from decimal64_conv.go; DO NOT EDIT.

package decimal

import "math"

// New32 returns coef × 10**exp, rounded to nearest even if coef has more
// than 7 digits. New32(1999, -2) is 19.99.
func New32(coef int64, exp int) Decimal32 {
	var c Context
	return c.New32(coef, exp)
}

// New32FromUint is like New32 for an unsigned coefficient.
func New32FromUint(coef uint64, exp int) Decimal32 {
	var c Context
	return c.New32FromUint(coef, exp)
}

// New32FromFloat returns the Decimal32 nearest to f: the exact binary value
// of f, rounded once, to nearest even. Values such as 2.5 that convert
// exactly get the exponent nearest zero. All others have as many digits as
// the format holds, not the few that would identify f: the float64 0.1 is
// exactly 0.1000000000000000055511151231257827..., and converts to that
// value rounded to 7 digits. To convert the way strconv prints,
// parse the output of strconv.FormatFloat instead.
func New32FromFloat(f float64) Decimal32 {
	var c Context
	return c.New32FromFloat(f)
}

// New32 returns coef × 10**exp, rounded according to the context if coef has
// more than 7 digits.
func (c *Context) New32(coef int64, exp int) Decimal32 {
	neg, mag := abs64(coef)
	return pack32(c.round(&format32, neg, uint128{0, mag}, clampExp(exp), false))
}

// New32FromUint is like New32 for an unsigned coefficient.
func (c *Context) New32FromUint(coef uint64, exp int) Decimal32 {
	return pack32(c.round(&format32, false, uint128{0, coef}, clampExp(exp), false))
}

// New32FromFloat returns f converted to a Decimal32, correctly rounded
// according to the context. A NaN converts to a quiet NaN.
func (c *Context) New32FromFloat(f float64) Decimal32 {
	switch {
	case math.IsNaN(f):
		return pack32(num{kind: quietNaN, neg: math.Signbit(f)})
	case math.IsInf(f, 0):
		return pack32(num{kind: infinite, neg: f < 0})
	}
	neg, coef, exp, sticky := fromFloat(f)
	return pack32(c.round(&format32, neg, coef, exp, sticky))
}

// Int64 returns x truncated toward zero to an int64, and whether that
// integer equals x. Values out of range, infinities included, convert to the
// nearest int64, and NaNs to zero; neither is exact.
func (x Decimal32) Int64() (v int64, exact bool) {
	n := x.unpack()
	return truncInt64(n.kind, n.neg, uint128{0, n.coef}, int(n.exp))
}

// Uint64 returns x truncated toward zero to a uint64, and whether that
// integer equals x. Values out of range, infinities included, convert to the
// nearest uint64, and NaNs to zero; neither is exact.
func (x Decimal32) Uint64() (v uint64, exact bool) {
	n := x.unpack()
	return truncUint64(n.kind, n.neg, uint128{0, n.coef}, int(n.exp))
}

// Float64 returns the float64 nearest to x, ties to even. Values too large
// for a float64 convert to an infinity.
func (x Decimal32) Float64() float64 {
	n := x.unpack()
	return toFloat(n.kind, n.neg, uint128{0, n.coef}, int(n.exp))
}

// Int64From32 returns x rounded to an integer according to the context. It
// raises Inexact if x is not an integer; callers wanting the plain
// convertToInteger operations of IEEE 754 rather than the convertToInteger
// Exact ones can ignore that. If x is a NaN, an infinity, or rounds to a
// value out of range, it raises Invalid and returns the nearest int64 (zero
// for a NaN).
func (c *Context) Int64From32(x Decimal32) int64 {
	n := x.unpack()
	return c.toInt64(n.kind, n.neg, uint128{0, n.coef}, int(n.exp))
}

// Uint64From32 is like Int64From32 for uint64.
func (c *Context) Uint64From32(x Decimal32) uint64 {
	n := x.unpack()
	return c.toUint64(n.kind, n.neg, uint128{0, n.coef}, int(n.exp))
}

// Float64From32 returns the float64 nearest to x, ties to even, raising
// Inexact, Overflow and Underflow as the conversion warrants and Invalid for
// a signaling NaN. The binary rounding direction is not affected by the
// context.
func (c *Context) Float64From32(x Decimal32) float64 {
	n := x.unpack()
	return c.toFloatFlags(n.kind, n.neg, uint128{0, n.coef}, int(n.exp))
}
