// Code generated by gen_formats.go from decimal64_text.go; DO NOT EDIT.

package decimal

import "fmt"

// Parse32 converts the string s to a Decimal32, rounding to nearest even if
// s has more than 7 significant digits.
//
// Parse32 accepts decimal numbers in plain or scientific notation
// ("-12.50", ".5", "1.25E+3"), infinities ("Inf", "-Infinity") and NaNs
// ("NaN", "sNaN", either optionally followed by a payload as in "NaN123"),
// all without regard to case. The exponent of the result follows the text,
// so "1.50" and "1.5" parse to different members of the same cohort.
//
// If s is not syntactically well-formed, Parse32 returns a quiet NaN and an
// error of type *strconv.NumError wrapping strconv.ErrSyntax. Overflow and
// underflow are not errors; use Context.Parse32 to observe them.
func Parse32(s string) (Decimal32, error) {
	var c Context
	return c.Parse32(s)
}

// MustParse32 is like Parse32 but panics if s cannot be parsed. It
// simplifies the initialization of package-level variables.
func MustParse32(s string) Decimal32 {
	x, err := Parse32(s)
	if err != nil {
		panic(err)
	}
	return x
}

// Parse32 is like the package-level Parse32 but rounds according to the
// context and raises Inexact, Overflow and Underflow as appropriate, and
// Invalid for a syntax error.
func (c *Context) Parse32(s string) (Decimal32, error) {
	n, err := c.parse(&format32, "Parse32", s)
	if err != nil {
		c.Flags |= Invalid
	}
	return pack32(n), err
}

// text unpacks x into t for conversion to characters.
func (x Decimal32) text(t *text) {
	n := x.unpack()
	t.neg, t.kind = n.neg, n.kind
	t.setCoef(uint128{0, n.coef}, int(n.exp))
}

// String returns x in the scientific notation defined by IEEE 754 and the
// General Decimal Arithmetic specification: plain digits when the exponent
// is small ("-12.50", "0.000001"), otherwise one digit before the point and
// an exponent ("1.25E+30"). Infinities are "Infinity" and "-Infinity"; NaNs
// are "NaN" or "sNaN", followed by the payload if it is non-zero.
//
// The string preserves the exponent, so Parse32(x.String()) recovers x
// exactly, including its position in its cohort.
func (x Decimal32) String() string {
	var t text
	var buf [48]byte
	x.text(&t)
	return string(t.appendSci(buf[:0]))
}

// Text converts x to a string in the given strconv-style format: 'e' or 'E'
// (-d.dddde±dd), 'f' or 'F' (-ddd.ddd), or 'g' or 'G' ('e' for large
// exponents, 'f' otherwise). The precision prec is the number of digits
// after the decimal point for 'e' and 'f' and the number of significant
// digits for 'g', which like strconv then omits trailing zeros; rounding to
// it is to nearest even. A negative precision formats x exactly, trailing
// zeros included.
func (x Decimal32) Text(format byte, prec int) string {
	var buf [64]byte
	return string(x.Append(buf[:0], format, prec))
}

// Append appends the Text form of x to b and returns the extended buffer.
func (x Decimal32) Append(b []byte, format byte, prec int) []byte {
	var t text
	x.text(&t)
	return t.append(b, format, prec)
}

// Format implements fmt.Formatter. It accepts %v and %s (as String), and
// %e, %E, %f, %F, %g and %G (as Text, with fmt's default precision of 6 for
// %e and %f), along with the usual width, precision and '+', '-', ' ' and
// '0' flags.
func (x Decimal32) Format(s fmt.State, verb rune) {
	var t text
	x.text(&t)
	t.format(s, verb, "Decimal32")
}

// AppendText implements encoding.TextAppender using the String form.
func (x Decimal32) AppendText(b []byte) ([]byte, error) {
	var t text
	x.text(&t)
	return t.appendSci(b), nil
}

// MarshalText implements encoding.TextMarshaler using the String form.
func (x Decimal32) MarshalText() ([]byte, error) { return x.AppendText(nil) }

// UnmarshalText implements encoding.TextUnmarshaler. It accepts the same
// syntax as Parse32.
func (x *Decimal32) UnmarshalText(b []byte) error {
	var c Context
	n, err := c.parseBytes(&format32, "Parse32", b)
	if err != nil {
		return err
	}
	*x = pack32(n)
	return nil
}
