// Code generated by gen_formats.go from decimal64_arith.go; DO NOT EDIT.

package decimal

// Add128 returns the sum x + y.
func (c *Context) Add128(x, y Decimal128) Decimal128 {
	return pack128(c.add128(x.unpack(), y.unpack()))
}

// Sub128 returns the difference x - y.
func (c *Context) Sub128(x, y Decimal128) Decimal128 {
	return pack128(c.sub128(x.unpack(), y.unpack()))
}

// Mul128 returns the product x × y.
func (c *Context) Mul128(x, y Decimal128) Decimal128 {
	return pack128(c.mul128(x.unpack(), y.unpack()))
}

// Quo128 returns the quotient x / y.
func (c *Context) Quo128(x, y Decimal128) Decimal128 {
	return pack128(c.quo128(x.unpack(), y.unpack()))
}

// FMA128 returns the fused multiply-add x × y + z: the exact product is added
// to z and the sum rounded once.
func (c *Context) FMA128(x, y, z Decimal128) Decimal128 {
	return pack128(c.fma128(x.unpack(), y.unpack(), z.unpack()))
}

// Sqrt128 returns the square root of x, correctly rounded. The square root
// of a negative number other than -0 is a NaN and raises Invalid.
func (c *Context) Sqrt128(x Decimal128) Decimal128 {
	return pack128(c.sqrt128(x.unpack()))
}

// FMA returns the fused multiply-add x × y + z, rounded once, to nearest
// even.
func (x Decimal128) FMA(y, z Decimal128) Decimal128 {
	var c Context
	return c.FMA128(x, y, z)
}

// Sqrt returns the square root of x, rounded to nearest even.
//
// The exponent of an exact square root is as close to half the exponent of
// x as the result allows, so the square root of 4.00 is 2.0.
func (x Decimal128) Sqrt() Decimal128 {
	var c Context
	return c.Sqrt128(x)
}

// Add returns the sum x + y, rounded to nearest even.
//
// The exponent of an exact sum is the smaller of the operands' exponents,
// so 1.5 + 0.25 is 1.75 and 1.50 + 1 is 2.50.
func (x Decimal128) Add(y Decimal128) Decimal128 {
	var c Context
	return c.Add128(x, y)
}

// Sub returns the difference x - y, rounded to nearest even.
func (x Decimal128) Sub(y Decimal128) Decimal128 {
	var c Context
	return c.Sub128(x, y)
}

// Mul returns the product x × y, rounded to nearest even.
//
// The exponent of an exact product is the sum of the operands' exponents,
// so 1.5 × 2.00 is 3.000.
func (x Decimal128) Mul(y Decimal128) Decimal128 {
	var c Context
	return c.Mul128(x, y)
}

// Quo returns the quotient x / y, rounded to nearest even. Division of a
// finite non-zero number by zero returns an infinity.
//
// The exponent of an exact quotient is as close to the difference of the
// operands' exponents as the result allows, so 6.0 / 2 is 3.0 and 1 / 4 is
// 0.25.
func (x Decimal128) Quo(y Decimal128) Decimal128 {
	var c Context
	return c.Quo128(x, y)
}
