// Code generated by gen_formats.go from decimal64_ops.go; DO NOT EDIT.

package decimal

// Compare32 compares x and y by value and returns Less, Equal, Greater, or
// Unordered if either is a NaN. It is the IEEE 754 quiet comparison: only a
// signaling NaN raises Invalid. Members of the same cohort, and zeros of
// either sign, compare Equal.
func (c *Context) Compare32(x, y Decimal32) Ordering {
	return c.compare(x.unpack(), y.unpack(), false)
}

// CompareSignal32 is like Compare32 but raises Invalid for any NaN operand,
// as the IEEE 754 signaling comparisons do.
func (c *Context) CompareSignal32(x, y Decimal32) Ordering {
	return c.compare(x.unpack(), y.unpack(), true)
}

// Min32 returns the smaller of x and y, or a NaN if either is a NaN
// (IEEE 754-2019 minimum). -0 is smaller than +0.
func (c *Context) Min32(x, y Decimal32) Decimal32 {
	return pack32(c.minMax(&format32, x.unpack(), y.unpack(), false, false, false))
}

// Max32 returns the larger of x and y, or a NaN if either is a NaN
// (IEEE 754-2019 maximum). +0 is larger than -0.
func (c *Context) Max32(x, y Decimal32) Decimal32 {
	return pack32(c.minMax(&format32, x.unpack(), y.unpack(), true, false, false))
}

// MinNum32 is like Min32 but treats a NaN as missing data: if exactly one
// operand is a NaN the other is returned (IEEE 754-2019 minimumNumber).
func (c *Context) MinNum32(x, y Decimal32) Decimal32 {
	return pack32(c.minMax(&format32, x.unpack(), y.unpack(), false, false, true))
}

// MaxNum32 is like Max32 but treats a NaN as missing data: if exactly one
// operand is a NaN the other is returned (IEEE 754-2019 maximumNumber).
func (c *Context) MaxNum32(x, y Decimal32) Decimal32 {
	return pack32(c.minMax(&format32, x.unpack(), y.unpack(), true, false, true))
}

// Quantize32 returns x rounded to the exponent of y. It raises Invalid and
// returns a NaN if the result would need more than 7 digits, or if exactly
// one operand is infinite.
func (c *Context) Quantize32(x, y Decimal32) Decimal32 {
	return pack32(c.quantizeTo(&format32, x.unpack(), y.unpack()))
}

// RoundToMultiple32 returns x rounded, in the direction of the context, to a
// multiple of y, which must be finite and positive. The result has the
// exponent of y, as Quantize32 gives it: 10.12 rounded to a multiple of 0.05
// is 10.10, and to a multiple of 0.25 is 10.00. Quantize32 is the special
// case of y a power of ten. It raises Inexact if the result differs from x,
// and Invalid, returning a NaN, if x is infinite, if y is not a finite
// positive number, or if the result would need more than 7 digits.
//
// The result divided by y is the number of multiples, an integer that Quo32
// returns exactly; in ToZero that is the integer quotient of x / y.
func (c *Context) RoundToMultiple32(x, y Decimal32) Decimal32 {
	return pack32(c.roundToMultiple(&format32, x.unpack(), y.unpack()))
}

// Quantum32 returns the quantum of x, 1 × 10**exponent: the value of one
// unit in the last place of its coefficient. The quantum of an infinity is
// +Inf.
func (c *Context) Quantum32(x Decimal32) Decimal32 {
	return pack32(c.quantum(&format32, x.unpack()))
}

// Round32 returns x rounded to the given number of decimal places, which may
// be negative to round to tens, hundreds and so on. Round32 only ever
// removes digits: a value with fewer decimal places is returned unchanged.
func (c *Context) Round32(x Decimal32, places int) Decimal32 {
	n := x.unpack()
	switch {
	case n.isNaN():
		return pack32(c.nan(&format32, n, n))
	case n.kind == infinite || int(n.exp) >= -places:
		return x
	}
	return pack32(c.quantize(&format32, n, max(-places, format32.emin)))
}

// RoundToIntegralExact32 rounds x to an integer in the rounding direction of
// the context, raising Inexact if the result differs from x.
func (c *Context) RoundToIntegralExact32(x Decimal32) Decimal32 {
	return pack32(c.roundToIntegral(&format32, x.unpack(), c.Rounding, true))
}

// RoundToIntegral32 rounds x to an integer in the given direction. Unlike
// RoundToIntegralExact32 it does not raise Inexact.
func (c *Context) RoundToIntegral32(x Decimal32, mode RoundingMode) Decimal32 {
	return pack32(c.roundToIntegral(&format32, x.unpack(), mode, false))
}

// NextUp32 returns the least Decimal32 that compares greater than x.
func (c *Context) NextUp32(x Decimal32) Decimal32 {
	return pack32(c.next(&format32, x.unpack(), true))
}

// NextDown32 returns the greatest Decimal32 that compares less than x.
func (c *Context) NextDown32(x Decimal32) Decimal32 {
	return pack32(c.next(&format32, x.unpack(), false))
}

// LogB32 returns the exponent of x as though x were normalized to one digit
// before the decimal point: floor(log10(|x|)). LogB32(±Inf) is +Inf;
// LogB32(0) is -Inf and raises DivisionByZero.
func (c *Context) LogB32(x Decimal32) Decimal32 {
	return pack32(c.logB(&format32, x.unpack()))
}

// ScaleB32 returns x × 10**n.
func (c *Context) ScaleB32(x Decimal32, n int) Decimal32 {
	return pack32(c.scaleB(&format32, x.unpack(), n))
}

// Reduce32 returns x with all trailing zeros removed from its coefficient,
// the simplest member of its cohort. All zeros reduce to 0E+0.
func (c *Context) Reduce32(x Decimal32) Decimal32 {
	return pack32(c.reduce(&format32, x.unpack()))
}

// Remainder32 returns the IEEE 754 remainder of x / y: x - y×n, where n is
// the integer nearest the exact quotient x / y, ties to even. The result is
// always exact and lies in [-|y|/2, |y|/2]. Compare math.Remainder.
func (c *Context) Remainder32(x, y Decimal32) Decimal32 {
	return pack32(c.rem(&format32, x.unpack(), y.unpack(), true))
}

// Mod32 returns the remainder of x / y with the quotient truncated toward
// zero, so the result has the sign of x and magnitude less than |y|. The
// result is always exact. Compare math.Mod.
func (c *Context) Mod32(x, y Decimal32) Decimal32 {
	return pack32(c.rem(&format32, x.unpack(), y.unpack(), false))
}

// Compare compares x and y by value and returns Less, Equal, Greater, or
// Unordered if either is a NaN.
func (x Decimal32) Compare(y Decimal32) Ordering {
	var c Context
	return c.Compare32(x, y)
}

// Equal reports whether x and y are equal in value. Members of the same
// cohort are equal, as are +0 and -0; a NaN is not equal to anything,
// itself included.
func (x Decimal32) Equal(y Decimal32) bool { return x.Compare(y) == Equal }

// Less reports whether x < y. It is false if either operand is a NaN.
func (x Decimal32) Less(y Decimal32) bool { return x.Compare(y) == Less }

// Cmp compares x and y by value and returns -1, 0 or +1. Like cmp.Compare
// on floating-point numbers, it treats a NaN as less than any number and
// equal to any other NaN, so that it is a consistent ordering for sorting:
//
//	slices.SortFunc(s, decimal.Decimal32.Cmp)
func (x Decimal32) Cmp(y Decimal32) int {
	switch o := x.Compare(y); {
	case o != Unordered:
		return int(o)
	case !x.IsNaN():
		return 1
	case !y.IsNaN():
		return -1
	}
	return 0
}

// CmpTotal compares the representations of x and y using the IEEE 754
// totalOrder relation and returns -1, 0 or +1. Unlike Cmp it distinguishes
// every pair of distinct canonical values:
//
//	-NaN < -sNaN < -Inf < -1.0 < -1.00 < -0 < +0 < 1.00 < 1.0 < +Inf < +sNaN < +NaN
//
// The totalOrder predicate of IEEE 754 is x.CmpTotal(y) <= 0.
func (x Decimal32) CmpTotal(y Decimal32) int { return cmpTotal(x.unpack(), y.unpack()) }

// Min returns the smaller of x and y, or a NaN if either is a NaN.
func (x Decimal32) Min(y Decimal32) Decimal32 {
	var c Context
	return c.Min32(x, y)
}

// Max returns the larger of x and y, or a NaN if either is a NaN.
func (x Decimal32) Max(y Decimal32) Decimal32 {
	var c Context
	return c.Max32(x, y)
}

// Quantize returns x rounded, to nearest even, to the exponent of y. For
// example, quantizing to 0.01 rounds to two decimal places and pads with
// zeros as necessary. The result is a NaN if it would need more than 7
// digits.
func (x Decimal32) Quantize(y Decimal32) Decimal32 {
	var c Context
	return c.Quantize32(x, y)
}

// RoundToMultiple returns x rounded, to nearest even, to a multiple of y,
// such as a tick size or a coin: 10.12 to a multiple of 0.05 is 10.10. The
// result has the exponent of y. See Context.RoundToMultiple32.
func (x Decimal32) RoundToMultiple(y Decimal32) Decimal32 {
	var c Context
	return c.RoundToMultiple32(x, y)
}

// Quantum returns the quantum of x, 1 × 10**exponent; the quantum of 12.50
// is 0.01.
func (x Decimal32) Quantum() Decimal32 {
	var c Context
	return c.Quantum32(x)
}

// SameQuantum reports whether x and y have the same exponent. Two NaNs, or
// two infinities, also have the same quantum.
func (x Decimal32) SameQuantum(y Decimal32) bool { return sameQuantum(x.unpack(), y.unpack()) }

// Round returns x rounded, to nearest even, to the given number of decimal
// places; see Context.Round32.
func (x Decimal32) Round(places int) Decimal32 {
	var c Context
	return c.Round32(x, places)
}

// RoundToIntegral returns x rounded to an integer in the given direction.
func (x Decimal32) RoundToIntegral(mode RoundingMode) Decimal32 {
	var c Context
	return c.RoundToIntegral32(x, mode)
}

// NextUp returns the least Decimal32 that compares greater than x.
func (x Decimal32) NextUp() Decimal32 {
	var c Context
	return c.NextUp32(x)
}

// NextDown returns the greatest Decimal32 that compares less than x.
func (x Decimal32) NextDown() Decimal32 {
	var c Context
	return c.NextDown32(x)
}

// LogB returns floor(log10(|x|)), the exponent of the most significant
// digit of x; see Context.LogB32.
func (x Decimal32) LogB() Decimal32 {
	var c Context
	return c.LogB32(x)
}

// ScaleB returns x × 10**n, rounded to nearest even if it is subnormal.
func (x Decimal32) ScaleB(n int) Decimal32 {
	var c Context
	return c.ScaleB32(x, n)
}

// Reduce returns x with all trailing zeros removed from its coefficient.
// Equal non-zero values reduce to identical representations, which makes
// x.Reduce().Bits() usable as a map key (zeros keep their sign).
func (x Decimal32) Reduce() Decimal32 {
	var c Context
	return c.Reduce32(x)
}

// Remainder returns the IEEE 754 remainder of x / y; see
// Context.Remainder32.
func (x Decimal32) Remainder(y Decimal32) Decimal32 {
	var c Context
	return c.Remainder32(x, y)
}

// Mod returns the remainder of x / y with the sign of x; see Context.Mod32.
func (x Decimal32) Mod(y Decimal32) Decimal32 {
	var c Context
	return c.Mod32(x, y)
}
