// Code generated by gen_formats.go from decimal64_ops.go; DO NOT EDIT.

package decimal

// Compare128 compares x and y by value and returns Less, Equal, Greater, or
// Unordered if either is a NaN. It is the IEEE 754 quiet comparison: only a
// signaling NaN raises Invalid. Members of the same cohort, and zeros of
// either sign, compare Equal.
func (c *Context) Compare128(x, y Decimal128) Ordering {
	return c.compare128(x.unpack(), y.unpack(), false)
}

// CompareSignal128 is like Compare128 but raises Invalid for any NaN operand,
// as the IEEE 754 signaling comparisons do.
func (c *Context) CompareSignal128(x, y Decimal128) Ordering {
	return c.compare128(x.unpack(), y.unpack(), true)
}

// Min128 returns the smaller of x and y, or a NaN if either is a NaN
// (IEEE 754-2019 minimum). -0 is smaller than +0.
func (c *Context) Min128(x, y Decimal128) Decimal128 {
	return pack128(c.minMax128(x.unpack(), y.unpack(), false, false, false))
}

// Max128 returns the larger of x and y, or a NaN if either is a NaN
// (IEEE 754-2019 maximum). +0 is larger than -0.
func (c *Context) Max128(x, y Decimal128) Decimal128 {
	return pack128(c.minMax128(x.unpack(), y.unpack(), true, false, false))
}

// MinNum128 is like Min128 but treats a NaN as missing data: if exactly one
// operand is a NaN the other is returned (IEEE 754-2019 minimumNumber).
func (c *Context) MinNum128(x, y Decimal128) Decimal128 {
	return pack128(c.minMax128(x.unpack(), y.unpack(), false, false, true))
}

// MaxNum128 is like Max128 but treats a NaN as missing data: if exactly one
// operand is a NaN the other is returned (IEEE 754-2019 maximumNumber).
func (c *Context) MaxNum128(x, y Decimal128) Decimal128 {
	return pack128(c.minMax128(x.unpack(), y.unpack(), true, false, true))
}

// Quantize128 returns x rounded to the exponent of y. It raises Invalid and
// returns a NaN if the result would need more than 34 digits, or if exactly
// one operand is infinite.
func (c *Context) Quantize128(x, y Decimal128) Decimal128 {
	return pack128(c.quantizeTo128(x.unpack(), y.unpack()))
}

// Round128 returns x rounded to the given number of decimal places, which may
// be negative to round to tens, hundreds and so on. Round128 only ever
// removes digits: a value with fewer decimal places is returned unchanged.
func (c *Context) Round128(x Decimal128, places int) Decimal128 {
	n := x.unpack()
	switch {
	case n.isNaN():
		return pack128(c.nan128(n, n))
	case n.kind == infinite || int(n.exp) >= -places:
		return x
	}
	return pack128(c.quantize128(n, max(-places, emin128)))
}

// RoundToIntegralExact128 rounds x to an integer in the rounding direction of
// the context, raising Inexact if the result differs from x.
func (c *Context) RoundToIntegralExact128(x Decimal128) Decimal128 {
	return pack128(c.roundToIntegral128(x.unpack(), c.Rounding, true))
}

// RoundToIntegral128 rounds x to an integer in the given direction. Unlike
// RoundToIntegralExact128 it does not raise Inexact.
func (c *Context) RoundToIntegral128(x Decimal128, mode RoundingMode) Decimal128 {
	return pack128(c.roundToIntegral128(x.unpack(), mode, false))
}

// NextUp128 returns the least Decimal128 that compares greater than x.
func (c *Context) NextUp128(x Decimal128) Decimal128 {
	return pack128(c.next128(x.unpack(), true))
}

// NextDown128 returns the greatest Decimal128 that compares less than x.
func (c *Context) NextDown128(x Decimal128) Decimal128 {
	return pack128(c.next128(x.unpack(), false))
}

// LogB128 returns the exponent of x as though x were normalized to one digit
// before the decimal point: floor(log10(|x|)). LogB128(±Inf) is +Inf;
// LogB128(0) is -Inf and raises DivisionByZero.
func (c *Context) LogB128(x Decimal128) Decimal128 {
	return pack128(c.logB128(x.unpack()))
}

// ScaleB128 returns x × 10**n.
func (c *Context) ScaleB128(x Decimal128, n int) Decimal128 {
	return pack128(c.scaleB128(x.unpack(), n))
}

// Reduce128 returns x with all trailing zeros removed from its coefficient,
// the simplest member of its cohort. All zeros reduce to 0E+0.
func (c *Context) Reduce128(x Decimal128) Decimal128 {
	return pack128(c.reduce128(x.unpack()))
}

// Remainder128 returns the IEEE 754 remainder of x / y: x - y×n, where n is
// the integer nearest the exact quotient x / y, ties to even. The result is
// always exact and lies in [-|y|/2, |y|/2]. Compare math.Remainder.
func (c *Context) Remainder128(x, y Decimal128) Decimal128 {
	return pack128(c.rem128(x.unpack(), y.unpack(), true))
}

// Mod128 returns the remainder of x / y with the quotient truncated toward
// zero, so the result has the sign of x and magnitude less than |y|. The
// result is always exact. Compare math.Mod.
func (c *Context) Mod128(x, y Decimal128) Decimal128 {
	return pack128(c.rem128(x.unpack(), y.unpack(), false))
}

// Compare compares x and y by value and returns Less, Equal, Greater, or
// Unordered if either is a NaN.
func (x Decimal128) Compare(y Decimal128) Ordering {
	var c Context
	return c.Compare128(x, y)
}

// Equal reports whether x and y are equal in value. Members of the same
// cohort are equal, as are +0 and -0; a NaN is not equal to anything,
// itself included.
func (x Decimal128) Equal(y Decimal128) bool { return x.Compare(y) == Equal }

// Less reports whether x < y. It is false if either operand is a NaN.
func (x Decimal128) Less(y Decimal128) bool { return x.Compare(y) == Less }

// Cmp compares x and y by value and returns -1, 0 or +1. Like cmp.Compare
// on floating-point numbers, it treats a NaN as less than any number and
// equal to any other NaN, so that it is a consistent ordering for sorting:
//
//	slices.SortFunc(s, decimal.Decimal128.Cmp)
func (x Decimal128) Cmp(y Decimal128) int {
	switch o := x.Compare(y); {
	case o != Unordered:
		return int(o)
	case !x.IsNaN():
		return 1
	case !y.IsNaN():
		return -1
	}
	return 0
}

// CmpTotal compares the representations of x and y using the IEEE 754
// totalOrder relation and returns -1, 0 or +1. Unlike Cmp it distinguishes
// every pair of distinct canonical values:
//
//	-NaN < -sNaN < -Inf < -1.0 < -1.00 < -0 < +0 < 1.00 < 1.0 < +Inf < +sNaN < +NaN
//
// The totalOrder predicate of IEEE 754 is x.CmpTotal(y) <= 0.
func (x Decimal128) CmpTotal(y Decimal128) int { return cmpTotal128(x.unpack(), y.unpack()) }

// Min returns the smaller of x and y, or a NaN if either is a NaN.
func (x Decimal128) Min(y Decimal128) Decimal128 {
	var c Context
	return c.Min128(x, y)
}

// Max returns the larger of x and y, or a NaN if either is a NaN.
func (x Decimal128) Max(y Decimal128) Decimal128 {
	var c Context
	return c.Max128(x, y)
}

// Quantize returns x rounded, to nearest even, to the exponent of y. For
// example, quantizing to 0.01 rounds to two decimal places and pads with
// zeros as necessary. The result is a NaN if it would need more than 34
// digits.
func (x Decimal128) Quantize(y Decimal128) Decimal128 {
	var c Context
	return c.Quantize128(x, y)
}

// SameQuantum reports whether x and y have the same exponent. Two NaNs, or
// two infinities, also have the same quantum.
func (x Decimal128) SameQuantum(y Decimal128) bool { return sameQuantum128(x.unpack(), y.unpack()) }

// Round returns x rounded, to nearest even, to the given number of decimal
// places; see Context.Round128.
func (x Decimal128) Round(places int) Decimal128 {
	var c Context
	return c.Round128(x, places)
}

// RoundToIntegral returns x rounded to an integer in the given direction.
func (x Decimal128) RoundToIntegral(mode RoundingMode) Decimal128 {
	var c Context
	return c.RoundToIntegral128(x, mode)
}

// NextUp returns the least Decimal128 that compares greater than x.
func (x Decimal128) NextUp() Decimal128 {
	var c Context
	return c.NextUp128(x)
}

// NextDown returns the greatest Decimal128 that compares less than x.
func (x Decimal128) NextDown() Decimal128 {
	var c Context
	return c.NextDown128(x)
}

// LogB returns floor(log10(|x|)), the exponent of the most significant
// digit of x; see Context.LogB128.
func (x Decimal128) LogB() Decimal128 {
	var c Context
	return c.LogB128(x)
}

// ScaleB returns x × 10**n, rounded to nearest even if it is subnormal.
func (x Decimal128) ScaleB(n int) Decimal128 {
	var c Context
	return c.ScaleB128(x, n)
}

// Reduce returns x with all trailing zeros removed from its coefficient.
// Equal non-zero values reduce to identical representations, which makes
// x.Reduce().Bits() usable as a map key (zeros keep their sign).
func (x Decimal128) Reduce() Decimal128 {
	var c Context
	return c.Reduce128(x)
}

// Remainder returns the IEEE 754 remainder of x / y; see
// Context.Remainder128.
func (x Decimal128) Remainder(y Decimal128) Decimal128 {
	var c Context
	return c.Remainder128(x, y)
}

// Mod returns the remainder of x / y with the sign of x; see Context.Mod128.
func (x Decimal128) Mod(y Decimal128) Decimal128 {
	var c Context
	return c.Mod128(x, y)
}
