// Code generated by gen_formats.go from dectest64_test.go; DO NOT EDIT.

package decimal

import (
	"strconv"
	"strings"
	"testing"
)

// arg32 converts a decTest operand, which is either a numeric string or '#'
// followed by the hexadecimal DPD encoding.
func arg32(s string) (Decimal32, error) {
	if len(s) > 0 && s[0] == '#' {
		x, ok := hexArg32(s)
		if !ok {
			return x, errSkip
		}
		return x, nil
	}
	var c Context
	x, err := c.Parse32(s)
	if err != nil || c.Flags != 0 {
		// Operands are meant to be representable; anything else is a test
		// of string conversion, which tosci and apply handle themselves.
		return x, errSkip
	}
	return x, nil
}

func args32(args []string) ([]Decimal32, error) {
	out := make([]Decimal32, len(args))
	for i, s := range args {
		x, err := arg32(s)
		if err != nil {
			return nil, err
		}
		out[i] = x
	}
	return out, nil
}

func unary32(f func(c *Context, x Decimal32) Decimal32) decOp {
	return func(c *Context, args []string) (string, error) {
		x, err := args32(args[:1])
		if err != nil {
			return "", err
		}
		return f(c, x[0]).String(), nil
	}
}

func binary32(f func(c *Context, x, y Decimal32) Decimal32) decOp {
	return func(c *Context, args []string) (string, error) {
		x, err := args32(args[:2])
		if err != nil {
			return "", err
		}
		return f(c, x[0], x[1]).String(), nil
	}
}

// compare32 adapts a comparison: decTest expects -1, 0, 1 or the propagated
// NaN.
func compare32(f func(c *Context, x, y Decimal32) Ordering) decOp {
	return binaryNaN32(func(c *Context, x, y Decimal32) string {
		return strconv.Itoa(int(f(c, x, y)))
	})
}

// binaryNaN32 wraps an operation whose IEEE 754 form does not return a
// decimal, or treats NaNs differently: decTest expects NaN operands to
// propagate as they do for arithmetic.
func binaryNaN32(f func(c *Context, x, y Decimal32) string) decOp {
	return func(c *Context, args []string) (string, error) {
		x, err := args32(args[:2])
		if err != nil {
			return "", err
		}
		if x[0].IsNaN() || x[1].IsNaN() {
			f(c, x[0], x[1]) // for the flags
			var quiet Context
			return pack32(quiet.nan(&format32, x[0].unpack(), x[1].unpack())).String(), nil
		}
		return f(c, x[0], x[1]), nil
	}
}

var decOps32 = map[string]decOp{
	"add":      binary32((*Context).Add32),
	"subtract": binary32((*Context).Sub32),
	"multiply": binary32((*Context).Mul32),
	"divide":   binary32((*Context).Quo32),
	"quantize": binary32((*Context).Quantize32),
	"fma": func(c *Context, args []string) (string, error) {
		x, err := args32(args[:3])
		if err != nil {
			return "", err
		}
		return c.FMA32(x[0], x[1], x[2]).String(), nil
	},
	"remaindernear": func(c *Context, args []string) (string, error) {
		if strings.Contains(decWantConds, "division_impossible") {
			return "", errSkip // a General Decimal Arithmetic restriction
		}
		return binary32((*Context).Remainder32)(c, args)
	},
	"remainder": func(c *Context, args []string) (string, error) {
		if strings.Contains(decWantConds, "division_impossible") {
			return "", errSkip
		}
		return binary32((*Context).Mod32)(c, args)
	},

	"compare":    compare32((*Context).Compare32),
	"comparesig": compare32((*Context).CompareSignal32),
	"comparetotal": func(c *Context, args []string) (string, error) {
		x, err := args32(args[:2])
		if err != nil {
			return "", err
		}
		return strconv.Itoa(x[0].CmpTotal(x[1])), nil
	},
	"comparetotmag": func(c *Context, args []string) (string, error) {
		x, err := args32(args[:2])
		if err != nil {
			return "", err
		}
		return strconv.Itoa(x[0].Abs().CmpTotal(x[1].Abs())), nil
	},
	"samequantum": func(c *Context, args []string) (string, error) {
		x, err := args32(args[:2])
		if err != nil {
			return "", err
		}
		return bool01(x[0].SameQuantum(x[1])), nil
	},

	// decTest max and min are maxNum and minNum of IEEE 754-2008, which
	// differ from maximumNumber and minimumNumber of 754-2019 only in
	// returning a NaN when an operand is a signaling NaN.
	"max":    minMax32(true, false),
	"min":    minMax32(false, false),
	"maxmag": minMax32(true, true),
	"minmag": minMax32(false, true),

	"tointegralx": unary32((*Context).RoundToIntegralExact32),
	"tointegral": unary32(func(c *Context, x Decimal32) Decimal32 {
		return c.RoundToIntegral32(x, c.Rounding)
	}),
	"nextplus":  unary32((*Context).NextUp32),
	"nextminus": unary32((*Context).NextDown32),
	"logb":      unary32((*Context).LogB32),
	"reduce":    unary32((*Context).Reduce32),
	"scaleb": func(c *Context, args []string) (string, error) {
		x, err := args32(args[:2])
		if err != nil {
			return "", err
		}
		// decTest takes the scale as a decimal and restricts its range.
		switch n, ok := scaleArg32(x[1]); {
		case x[0].IsNaN() || x[1].IsNaN():
			return pack32(c.nan(&format32, x[0].unpack(), x[1].unpack())).String(), nil
		case !ok:
			return pack32(c.invalid()).String(), nil
		default:
			return c.ScaleB32(x[0], n).String(), nil
		}
	},

	// plus, minus and abs are arithmetic in decTest (0+x, 0-x), unlike the
	// quiet sign operations of IEEE 754.
	"plus": unary32(func(c *Context, x Decimal32) Decimal32 {
		return c.Add32(zeroLike32(x), x)
	}),
	"minus": unary32(func(c *Context, x Decimal32) Decimal32 {
		return c.Sub32(zeroLike32(x), x)
	}),
	"abs": unary32(func(c *Context, x Decimal32) Decimal32 {
		if x.Signbit() && !x.IsNaN() {
			return c.Sub32(zeroLike32(x), x)
		}
		return c.Add32(zeroLike32(x), x)
	}),
	"copy":       noHex(unary32(func(c *Context, x Decimal32) Decimal32 { return x })),
	"copyabs":    noHex(unary32(func(c *Context, x Decimal32) Decimal32 { return x.Abs() })),
	"copynegate": noHex(unary32(func(c *Context, x Decimal32) Decimal32 { return x.Neg() })),
	"copysign":   noHex(binary32(func(c *Context, x, y Decimal32) Decimal32 { return x.CopySign(y) })),
	"class": func(c *Context, args []string) (string, error) {
		x, err := args32(args[:1])
		if err != nil {
			return "", err
		}
		return decClassNames[x[0].Class()], nil
	},

	"canonical": unary32(func(c *Context, x Decimal32) Decimal32 { return x.Canonical() }),
	"tosci":     apply32,
	"apply":     apply32,
}

// apply32 converts the operand under the context, which is all that tosci
// and apply do.
func apply32(c *Context, args []string) (string, error) {
	if len(args[0]) > 0 && args[0][0] == '#' {
		x, err := arg32(args[0])
		return x.String(), err
	}
	x, _ := c.Parse32(args[0])
	return x.String(), nil
}

func minMax32(max, mag bool) decOp {
	return binary32(func(c *Context, x, y Decimal32) Decimal32 {
		if x.IsSignaling() || y.IsSignaling() {
			return pack32(c.nan(&format32, x.unpack(), y.unpack()))
		}
		return pack32(c.minMax(&format32, x.unpack(), y.unpack(), max, mag, true))
	})
}

func TestDecTest32(t *testing.T) { runDecTests(t, "ds*.decTest", decOps32, hex32) }
