// Code generated by gen_formats.go from dectest64_test.go; DO NOT EDIT.

package decimal

import (
	"strconv"
	"strings"
	"testing"
)

// arg128 converts a decTest operand, which is either a numeric string or '#'
// followed by the hexadecimal DPD encoding.
func arg128(s string) (Decimal128, error) {
	if len(s) > 0 && s[0] == '#' {
		x, ok := hexArg128(s)
		if !ok {
			return x, errSkip
		}
		return x, nil
	}
	var c Context
	x, err := c.Parse128(s)
	if err != nil || c.Flags != 0 {
		// Operands are meant to be representable; anything else is a test
		// of string conversion, which tosci and apply handle themselves.
		return x, errSkip
	}
	return x, nil
}

func args128(args []string) ([]Decimal128, error) {
	out := make([]Decimal128, len(args))
	for i, s := range args {
		x, err := arg128(s)
		if err != nil {
			return nil, err
		}
		out[i] = x
	}
	return out, nil
}

func unary128(f func(c *Context, x Decimal128) Decimal128) decOp {
	return func(c *Context, args []string) (string, error) {
		x, err := args128(args[:1])
		if err != nil {
			return "", err
		}
		return f(c, x[0]).String(), nil
	}
}

func binary128(f func(c *Context, x, y Decimal128) Decimal128) decOp {
	return func(c *Context, args []string) (string, error) {
		x, err := args128(args[:2])
		if err != nil {
			return "", err
		}
		return f(c, x[0], x[1]).String(), nil
	}
}

// compare128 adapts a comparison: decTest expects -1, 0, 1 or the propagated
// NaN.
func compare128(f func(c *Context, x, y Decimal128) Ordering) decOp {
	return binaryNaN128(func(c *Context, x, y Decimal128) string {
		return strconv.Itoa(int(f(c, x, y)))
	})
}

// binaryNaN128 wraps an operation whose IEEE 754 form does not return a
// decimal, or treats NaNs differently: decTest expects NaN operands to
// propagate as they do for arithmetic.
func binaryNaN128(f func(c *Context, x, y Decimal128) string) decOp {
	return func(c *Context, args []string) (string, error) {
		x, err := args128(args[:2])
		if err != nil {
			return "", err
		}
		if x[0].IsNaN() || x[1].IsNaN() {
			f(c, x[0], x[1]) // for the flags
			var quiet Context
			return pack128(quiet.nan128(x[0].unpack(), x[1].unpack())).String(), nil
		}
		return f(c, x[0], x[1]), nil
	}
}

var decOps128 = map[string]decOp{
	"add":      binary128((*Context).Add128),
	"subtract": binary128((*Context).Sub128),
	"multiply": binary128((*Context).Mul128),
	"divide":   binary128((*Context).Quo128),
	"quantize": binary128((*Context).Quantize128),
	"fma": func(c *Context, args []string) (string, error) {
		x, err := args128(args[:3])
		if err != nil {
			return "", err
		}
		return c.FMA128(x[0], x[1], x[2]).String(), nil
	},
	"remaindernear": func(c *Context, args []string) (string, error) {
		if strings.Contains(decWantConds, "division_impossible") {
			return "", errSkip // a General Decimal Arithmetic restriction
		}
		return binary128((*Context).Remainder128)(c, args)
	},
	"remainder": func(c *Context, args []string) (string, error) {
		if strings.Contains(decWantConds, "division_impossible") {
			return "", errSkip
		}
		return binary128((*Context).Mod128)(c, args)
	},

	"compare":    compare128((*Context).Compare128),
	"comparesig": compare128((*Context).CompareSignal128),
	"comparetotal": func(c *Context, args []string) (string, error) {
		x, err := args128(args[:2])
		if err != nil {
			return "", err
		}
		return strconv.Itoa(x[0].CmpTotal(x[1])), nil
	},
	"comparetotmag": func(c *Context, args []string) (string, error) {
		x, err := args128(args[:2])
		if err != nil {
			return "", err
		}
		return strconv.Itoa(x[0].Abs().CmpTotal(x[1].Abs())), nil
	},
	"samequantum": func(c *Context, args []string) (string, error) {
		x, err := args128(args[:2])
		if err != nil {
			return "", err
		}
		return bool01(x[0].SameQuantum(x[1])), nil
	},

	// decTest max and min are maxNum and minNum of IEEE 754-2008, which
	// differ from maximumNumber and minimumNumber of 754-2019 only in
	// returning a NaN when an operand is a signaling NaN.
	"max":    minMax128(true, false),
	"min":    minMax128(false, false),
	"maxmag": minMax128(true, true),
	"minmag": minMax128(false, true),

	"tointegralx": unary128((*Context).RoundToIntegralExact128),
	"tointegral": unary128(func(c *Context, x Decimal128) Decimal128 {
		return c.RoundToIntegral128(x, c.Rounding)
	}),
	"nextplus":  unary128((*Context).NextUp128),
	"nextminus": unary128((*Context).NextDown128),
	"logb":      unary128((*Context).LogB128),
	"reduce":    unary128((*Context).Reduce128),
	"scaleb": func(c *Context, args []string) (string, error) {
		x, err := args128(args[:2])
		if err != nil {
			return "", err
		}
		// decTest takes the scale as a decimal and restricts its range.
		switch n, ok := scaleArg128(x[1]); {
		case x[0].IsNaN() || x[1].IsNaN():
			return pack128(c.nan128(x[0].unpack(), x[1].unpack())).String(), nil
		case !ok:
			return pack128(c.invalid128()).String(), nil
		default:
			return c.ScaleB128(x[0], n).String(), nil
		}
	},

	// plus, minus and abs are arithmetic in decTest (0+x, 0-x), unlike the
	// quiet sign operations of IEEE 754.
	"plus": unary128(func(c *Context, x Decimal128) Decimal128 {
		return c.Add128(zeroLike128(x), x)
	}),
	"minus": unary128(func(c *Context, x Decimal128) Decimal128 {
		return c.Sub128(zeroLike128(x), x)
	}),
	"abs": unary128(func(c *Context, x Decimal128) Decimal128 {
		if x.Signbit() && !x.IsNaN() {
			return c.Sub128(zeroLike128(x), x)
		}
		return c.Add128(zeroLike128(x), x)
	}),
	"copy":       noHex(unary128(func(c *Context, x Decimal128) Decimal128 { return x })),
	"copyabs":    noHex(unary128(func(c *Context, x Decimal128) Decimal128 { return x.Abs() })),
	"copynegate": noHex(unary128(func(c *Context, x Decimal128) Decimal128 { return x.Neg() })),
	"copysign":   noHex(binary128(func(c *Context, x, y Decimal128) Decimal128 { return x.CopySign(y) })),
	"class": func(c *Context, args []string) (string, error) {
		x, err := args128(args[:1])
		if err != nil {
			return "", err
		}
		return decClassNames[x[0].Class()], nil
	},

	"canonical": unary128(func(c *Context, x Decimal128) Decimal128 { return x.Canonical() }),
	"tosci":     apply128,
	"apply":     apply128,
}

// apply128 converts the operand under the context, which is all that tosci
// and apply do.
func apply128(c *Context, args []string) (string, error) {
	if len(args[0]) > 0 && args[0][0] == '#' {
		x, err := arg128(args[0])
		return x.String(), err
	}
	x, _ := c.Parse128(args[0])
	return x.String(), nil
}

func minMax128(max, mag bool) decOp {
	return binary128(func(c *Context, x, y Decimal128) Decimal128 {
		if x.IsSignaling() || y.IsSignaling() {
			return pack128(c.nan128(x.unpack(), y.unpack()))
		}
		return pack128(c.minMax128(x.unpack(), y.unpack(), max, mag, true))
	})
}

func TestDecTest128(t *testing.T) { runDecTests(t, "dq*.decTest", decOps128, hex128) }
