//go:build ignore

// This program derives the Decimal32 and Decimal128 method sets from the
// Decimal64 ones. The three types have identical APIs that differ only in
// names, in the kernel they call and in a few numbers in the documentation,
// so decimal64_*.go is the single source of truth. Run it with "go generate".
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"strings"
)

// sources are the files to derive; "64" in the name becomes the width.
var sources = []string{
	"decimal64_arith.go",
	"decimal64_ops.go",
	"decimal64_text.go",
	"decimal64_conv.go",
	"dectest64_test.go",
}

// names are the identifiers that carry the format width as a suffix: the
// exported API, then the helpers of the test adapters.
const names = `Add|Sub|Mul|Quo|FMA|Sqrt|Compare|CompareSignal|Min|Max|MinNum|MaxNum|` +
	`Quantize|Round|RoundToIntegralExact|RoundToIntegral|NextUp|NextDown|LogB|ScaleB|` +
	`Reduce|Remainder|Mod|Parse|MustParse|New|Inf|NaN|NewNaN|` +
	`arg|args|unary|binary|compare|binaryNaN|minMax|apply|hex|hexArg|zeroLike|scaleArg|` +
	`decOps|TestDecTest`

type rule struct {
	re   *regexp.Regexp
	repl string
}

func rules(width, digits, testPrefix string, wide bool) []rule {
	var rs []rule
	add := func(re, repl string) { rs = append(rs, rule{regexp.MustCompile(re), repl}) }
	if wide {
		// The 128-bit kernel is a separate set of functions with a fixed
		// format and uint128 coefficients.
		add(`format64\.emin`, `emin128`)
		add(`\b(\w+)\.(\w+)\(&format64, `, `${1}.${2}128(`)
		add(`\(&format64\)`, `()`)
		add(`\bc\.invalid\(\)`, `c.invalid128()`)
		add(`uint128\{0, n\.coef\}`, `n.coef`)
		add(`\b(sameQuantum|cmpTotal)\(`, `${1}128(`)
	}
	add(`"dd\*`, `"`+testPrefix+`*`)
	add(`\bDecimal64\b`, `Decimal`+width)
	add(`\bdecimal64\b`, `decimal`+width)
	add(`\b(format|pack)64\b`, `${1}`+width)
	add(`\b(`+names+`)64\b`, `${1}`+width)
	add(`\bNew64From`, `New`+width+`From`)
	add(`From64\b`, `From`+width)
	return rs
}

var (
	commentNumber = regexp.MustCompile(`\b16\b`)
	header        = regexp.MustCompile(`(?m)^package decimal$`)
)

func main() {
	for _, target := range []struct {
		width, digits, testPrefix string
		wide                      bool
	}{{"32", "7", "ds", false}, {"128", "34", "dq", true}} {
		rs := rules(target.width, target.digits, target.testPrefix, target.wide)
		for _, in := range sources {
			data, err := os.ReadFile(in)
			if err != nil {
				log.Fatal(err)
			}
			lines := strings.Split(string(data), "\n")
			for i, line := range lines {
				if strings.HasPrefix(strings.TrimSpace(line), "//") {
					line = commentNumber.ReplaceAllString(line, target.digits)
				}
				for _, r := range rs {
					line = r.re.ReplaceAllString(line, r.repl)
				}
				lines[i] = line
			}
			out := strings.Join(lines, "\n")
			out = header.ReplaceAllString(out,
				fmt.Sprintf("// Code generated by gen_formats.go from %s; DO NOT EDIT.\n\npackage decimal", in))
			formatted, err := format.Source([]byte(out))
			if err != nil {
				log.Fatalf("%s for %s: %v", in, target.width, err)
			}
			name := strings.Replace(in, "64", target.width, 1)
			if old, _ := os.ReadFile(name); !bytes.Equal(old, formatted) {
				if err := os.WriteFile(name, formatted, 0o644); err != nil {
					log.Fatal(err)
				}
			}
		}
	}
}
