//go:build ignore

// This program generates tables.go. Run it with "go generate".
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"math/big"
	"os"
)

func main() {
	var b bytes.Buffer
	b.WriteString("// Code generated by gen_tables.go; DO NOT EDIT.\n\npackage decimal\n\n")

	mask := new(big.Int).SetUint64(^uint64(0))
	ten := big.NewInt(10)

	b.WriteString("// pow10tab[i] is 10**i.\nvar pow10tab = [20]uint64{\n")
	p := big.NewInt(1)
	for i := 0; i < 20; i++ {
		fmt.Fprintf(&b, "%s,\n", p)
		p.Mul(p, ten)
	}
	b.WriteString("}\n\n")

	b.WriteString("// pow10tab128[i] is 10**i.\nvar pow10tab128 = [39]uint128{\n")
	p = big.NewInt(1)
	for i := 0; i < 39; i++ {
		hi := new(big.Int).Rsh(p, 64)
		lo := new(big.Int).And(p, mask)
		fmt.Fprintf(&b, "{%#x, %#x}, // 1e%d\n", hi, lo, i)
		p.Mul(p, ten)
	}
	b.WriteString("}\n\n")

	// 256-bit powers of ten, used by the 128-bit kernel. Words are
	// little-endian, matching uint256.
	b.WriteString("// pow10tab256[i] is 10**i.\nvar pow10tab256 = [78]uint256{\n")
	p = big.NewInt(1)
	for i := 0; i < 78; i++ {
		var w [4]*big.Int
		q := new(big.Int).Set(p)
		for j := range w {
			w[j] = new(big.Int).And(q, mask)
			q.Rsh(q, 64)
		}
		fmt.Fprintf(&b, "{%#x, %#x, %#x, %#x}, // 1e%d\n", w[0], w[1], w[2], w[3], i)
		p.Mul(p, ten)
	}
	b.WriteString("}\n\n")

	// Densely packed decimal: declet <-> three decimal digits.
	b.WriteString("// dpd2bin[d] is the value in [0, 999] of the 10-bit DPD declet d.\nvar dpd2bin = [1024]uint16{\n")
	var bin2dpd [1000]uint16
	for d := 0; d < 1024; d++ {
		v := decodeDeclet(uint16(d))
		fmt.Fprintf(&b, "%d,", v)
		if d%16 == 15 {
			b.WriteByte('\n')
		}
	}
	b.WriteString("}\n\n")
	for v := 0; v < 1000; v++ {
		bin2dpd[v] = encodeDeclet(v)
		if decodeDeclet(bin2dpd[v]) != uint16(v) {
			log.Fatalf("declet round trip failed for %d", v)
		}
	}
	b.WriteString("// bin2dpd[v] is the canonical 10-bit DPD declet for v in [0, 999].\nvar bin2dpd = [1000]uint16{\n")
	for v, d := range bin2dpd {
		fmt.Fprintf(&b, "%#x,", d)
		if v%10 == 9 {
			b.WriteByte('\n')
		}
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("tables.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// encodeDeclet packs three decimal digits into a canonical DPD declet
// following IEEE 754-2008 table 3.4. Digit bits are (a,b,c,d) (e,f,g,h)
// (i,j,k,m); declet bits are p,q,r,s,t,u,v,w,x,y from most significant.
func encodeDeclet(v int) uint16 {
	d2, d1, d0 := v/100, v/10%10, v%10
	bit := func(x, n int) uint16 { return uint16(x>>n) & 1 }
	a, bb, c, d := bit(d2, 3), bit(d2, 2), bit(d2, 1), bit(d2, 0)
	e, f, g, h := bit(d1, 3), bit(d1, 2), bit(d1, 1), bit(d1, 0)
	i, j, k, m := bit(d0, 3), bit(d0, 2), bit(d0, 1), bit(d0, 0)
	var p, q, r, s, t, u, vv, w, x, y uint16
	switch a<<2 | e<<1 | i {
	case 0b000:
		p, q, r, s, t, u, vv, w, x, y = bb, c, d, f, g, h, 0, j, k, m
	case 0b001:
		p, q, r, s, t, u, vv, w, x, y = bb, c, d, f, g, h, 1, 0, 0, m
	case 0b010:
		p, q, r, s, t, u, vv, w, x, y = bb, c, d, j, k, h, 1, 0, 1, m
	case 0b100:
		p, q, r, s, t, u, vv, w, x, y = j, k, d, f, g, h, 1, 1, 0, m
	case 0b110:
		p, q, r, s, t, u, vv, w, x, y = j, k, d, 0, 0, h, 1, 1, 1, m
	case 0b101:
		p, q, r, s, t, u, vv, w, x, y = f, g, d, 0, 1, h, 1, 1, 1, m
	case 0b011:
		p, q, r, s, t, u, vv, w, x, y = bb, c, d, 1, 0, h, 1, 1, 1, m
	case 0b111:
		p, q, r, s, t, u, vv, w, x, y = 0, 0, d, 1, 1, h, 1, 1, 1, m
	}
	return p<<9 | q<<8 | r<<7 | s<<6 | t<<5 | u<<4 | vv<<3 | w<<2 | x<<1 | y
}

// decodeDeclet unpacks any of the 1024 declets (including the 24
// non-canonical ones) following IEEE 754-2008 table 3.3.
func decodeDeclet(dpd uint16) uint16 {
	bit := func(n int) uint16 { return dpd >> n & 1 }
	p, q, r, s, t, u, v, w, x, y := bit(9), bit(8), bit(7), bit(6), bit(5), bit(4), bit(3), bit(2), bit(1), bit(0)
	var d2, d1, d0 uint16
	switch {
	case v == 0:
		d2, d1, d0 = p<<2|q<<1|r, s<<2|t<<1|u, w<<2|x<<1|y
	case w == 0 && x == 0:
		d2, d1, d0 = p<<2|q<<1|r, s<<2|t<<1|u, 8|y
	case w == 0 && x == 1:
		d2, d1, d0 = p<<2|q<<1|r, 8|u, s<<2|t<<1|y
	case w == 1 && x == 0:
		d2, d1, d0 = 8|r, s<<2|t<<1|u, p<<2|q<<1|y
	case s == 0 && t == 0:
		d2, d1, d0 = 8|r, 8|u, p<<2|q<<1|y
	case s == 0 && t == 1:
		d2, d1, d0 = 8|r, p<<2|q<<1|u, 8|y
	case s == 1 && t == 0:
		d2, d1, d0 = p<<2|q<<1|r, 8|u, 8|y
	default:
		d2, d1, d0 = 8|r, 8|u, 8|y
	}
	return d2*100 + d1*10 + d0
}
